openapi: 3.0.3
info:
  title: FreeAgent
  version: 1.0.0
  contact: {}
servers:
- url: https://api.freeagent.com
  description: Production
- url: https://api.sandbox.freeagent.com
  description: Sandbox
paths:
  /v2/bank_accounts:
    get:
      tags:
      - Bank Accounts
      summary: List Bank Accounts
      description: List Bank Accounts
      operationId: listBankAccounts
      parameters:
      - name: view
        in: query
        schema:
          type: string
          example: standard_bank_accounts
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
  /v2/bank_accounts/{id}:
    get:
      tags:
      - Bank Accounts
      summary: Show Bank Account
      description: Show Bank Account
      operationId: showBankAccount
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: string
        example: ''
  /v2/bank_transaction_explanations:
    get:
      tags:
      - Bank Transaction Explanations
      summary: List all bank transaction explanations
      description: List all bank transaction explanations
      operationId: listAllBankTransactionExplanations
      parameters:
      - name: from_date
        in: query
        schema:
          type: string
          example: 2018-01-01
      - name: to_date
        in: query
        schema:
          type: string
          example: 2018-01-01
      - name: updated_since
        in: query
        schema:
          type: string
          example: 2018-01-01
      - name: bank_account
        in: query
        schema:
          type: string
          example: https://api.freeagent.com/v2/bank_accounts/:id
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
    post:
      tags:
      - Bank Transaction Explanations
      summary: Create a bank transaction explanation
      description: Create a bank transaction explanation
      operationId: createABankTransactionExplanation
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                bank_transaction_explanation:
                  $ref: '#/components/schemas/BankTransactionExplanationCreatePayload'
            examples:
              Create a bank transaction explanation:
                value:
                  bank_transaction_explanation:
                    attachment:
                      data: iVBORw0KGgo...
                      file_name: receipt.pdf
                      content_type: application/x-pdf
                    bank_account: https://api.freeagent.com/v2/bank_accounts/1
                    bank_transaction: https://api.freeagent.com/v2/bank_transactions/8
                    category: https://api.freeagent.com/v2/categories/285
                    dated_on: 2010-05-01
                    description: harness end-to-end e-business
                    gross_value: '-730.0'
                    project: https://api.freeagent.com/v2/projects/1
                    rebill_factor: '0.25'
                    rebill_type: markup
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
  /v2/bank_transaction_explanations/{id}:
    get:
      tags:
      - Bank Transaction Explanations
      summary: Get a single bank transaction explanation
      description: Get a single bank transaction explanation
      operationId: getASingleBankTransactionExplanation
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
    put:
      tags:
      - Bank Transaction Explanations
      summary: Update a bank transaction explanation
      description: Update a bank transaction explanation
      operationId: updateABankTransactionExplanation
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                bank_transaction_explanation:
                  $ref: '#/components/schemas/BankTransactionExplanationUpdatePayload'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
    delete:
      tags:
      - Bank Transaction Explanations
      summary: Delete a bank transaction explanation
      description: Delete a bank transaction explanation
      operationId: deleteABankTransactionExplanation
      responses:
        '200':
          description: Success
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: string
        example: ''
  /v2/bank_transactions:
    get:
      tags:
      - Bank Transactions
      summary: List all bank transactions under a certain bank account
      description: List all bank transactions under a certain bank account
      operationId: listAllBankTransactionsUnderACertainBankAccount
      parameters:
      - name: bank_account
        in: query
        schema:
          type: string
          example: https://api.freeagent.com/v2/bank_accounts/1
      - name: from_date
        in: query
        schema:
          type: string
          example: 2018-01-01
      - name: to_date
        in: query
        schema:
          type: string
          example: 2018-01-01
      - name: updated_since
        in: query
        schema:
          type: string
          example: 2018-01-01
      - name: view
        in: query
        schema:
          type: string
          example: all
      - name: last_uploaded
        in: query
        schema:
          type: string
          example: 'true'
      - name: page
        in: query
        schema:
          type: integer
          example: 1
      - name: per_page
        in: query
        schema:
          type: integer
          example: 100
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
  /v2/bank_transactions/{id}:
    get:
      tags:
      - Bank Transactions
      summary: Get a single bank transaction
      description: Get a single bank transaction
      operationId: getASingleBankTransaction
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: string
        example: ''
  /v2/bills:
    post:
      tags:
      - Bills
      summary: Create Bill
      description: Create Bill
      operationId: createBill
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                bill:
                  $ref: '#/components/schemas/BillCreatePayload'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
  /v2/categories:
    get:
      tags:
      - Categories
      summary: List Categories
      description: List Categories
      operationId: listCategories
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
  /v2/company:
    get:
      tags:
      - Company
      summary: Company Details
      description: Company Details
      operationId: companyDetails
      responses:
        '200':
          description: Company details
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
  /v2/contacts:
    get:
      tags:
      - Contacts
      summary: List Contacts
      description: List Contacts
      operationId: listContacts
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
    post:
      tags:
      - Contacts
      summary: Create Contact
      description: Create Contact
      operationId: createContact
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                contact:
                  $ref: '#/components/schemas/ContactCreatePayload'
            examples:
              Create Contact:
                value:
                  contact:
                    organisation_name: Testington & Sons Ltd
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
  /v2/expenses:
    get:
      tags:
      - Expenses
      summary: List all expenses
      description: List all expenses
      operationId: listAllExpenses
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
    post:
      tags:
      - Expenses
      summary: Create expense
      description: Create expense
      operationId: createExpense
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                expense:
                  $ref: '#/components/schemas/ExpensePayload'
                expenses:
                  type: array
                  items:
                    $ref: '#/components/schemas/ExpensePayload'
                  example:
                  - category: https://api.freeagent.com/v2/categories/285
                    created_at: 2011-08-24 08:10:40+00:00
                    dated_on: 2011-08-24
                    description: Some description
                    gross_value: '-12.0'
                    manual_sales_tax_amount: '0.12'
                    sales_tax_rate: '20.0'
                    updated_at: 2011-08-24 08:10:40+00:00
                    user: https://api.freeagent.com/v2/users/1
                  - category: https://api.freeagent.com/v2/categories/285
                    created_at: 2011-08-25 08:10:40+00:00
                    dated_on: 2011-08-24
                    description: Some description
                    gross_value: '-5.0'
                    manual_sales_tax_amount: '0.12'
                    sales_tax_rate: '20.0'
                    updated_at: 2011-08-25 08:10:40+00:00
                    user: https://api.freeagent.com/v2/users/1
            examples:
              Batch create expenses:
                value:
                  expenses:
                  - category: https://api.freeagent.com/v2/categories/285
                    created_at: 2011-08-24 08:10:40+00:00
                    dated_on: 2011-08-24
                    description: Some description
                    gross_value: '-12.0'
                    manual_sales_tax_amount: '0.12'
                    sales_tax_rate: '20.0'
                    updated_at: 2011-08-24 08:10:40+00:00
                    user: https://api.freeagent.com/v2/users/1
                  - category: https://api.freeagent.com/v2/categories/285
                    created_at: 2011-08-25 08:10:40+00:00
                    dated_on: 2011-08-24
                    description: Some description
                    gross_value: '-5.0'
                    manual_sales_tax_amount: '0.12'
                    sales_tax_rate: '20.0'
                    updated_at: 2011-08-25 08:10:40+00:00
                    user: https://api.freeagent.com/v2/users/1
              Create expense:
                value:
                  expense:
                    category: https://api.freeagent.com/v2/categories/285
                    created_at: 2011-08-24 08:10:40+00:00
                    currency: USD
                    dated_on: 2011-08-24
                    description: Some description
                    gross_value: '-20.0'
                    manual_sales_tax_amount: '0.12'
                    native_gross_value: '-12.0'
                    native_sales_tax_value: '-0.12'
                    sales_tax_rate: '1.0'
                    sales_tax_value: '-0.2'
                    updated_at: 2011-08-24 08:10:40+00:00
                    user: https://api.freeagent.com/v2/users/:id
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
  /v2/expenses/{id}:
    get:
      tags:
      - Expenses
      summary: Get a single expense
      description: Get a single expense
      operationId: getASingleExpense
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: string
        example: ''
  /v2/invoices/{id}/transitions/mark_as_sent:
    put:
      tags:
      - Invoices
      - Invoice Transitions
      summary: Mark invoice as sent
      description: Mark invoice as sent
      operationId: markInvoiceAsSent
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
        default:
          $ref: '#/components/responses/ErrorResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: string
        example: ''
  /v2/invoices/{id}/transitions/mark_as_cancelled:
    put:
      tags:
      - Invoices
      - Invoice Transitions
      summary: Mark invoice as cancelled
      description: Mark invoice as cancelled
      operationId: markInvoiceAsCancelled
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
        default:
          $ref: '#/components/responses/ErrorResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: string
        example: ''
  /v2/invoices/{id}/transitions/mark_as_scheduled:
    put:
      tags:
      - Invoices
      - Invoice Transitions
      summary: Mark invoice as scheduled
      description: Mark invoice as scheduled
      operationId: markInvoiceAsScheduled
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
        default:
          $ref: '#/components/responses/ErrorResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: string
        example: ''
  /v2/invoices/{id}/transitions/mark_as_draft:
    put:
      tags:
      - Invoices
      - Invoice Transitions
      summary: Mark invoice as draft
      description: Mark invoice as draft
      operationId: markInvoiceAsDraft
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
        default:
          $ref: '#/components/responses/ErrorResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: string
        example: ''
  /v2/invoices:
    get:
      tags:
      - Invoices
      summary: List Invoices
      description: List Invoices
      operationId: listInvoices
      parameters:
      - name: nested_invoice_items
        in: query
        description: Include nested invoice items in response
        schema:
          type: boolean
          example: true
      - name: contact
        in: query
        description: Filter invoices by contact URL
        schema:
          type: string
          example: https://api.freeagent.com/v2/contacts/:id
      - name: project
        in: query
        description: Filter invoices by project URL
        schema:
          type: string
          example: https://api.freeagent.com/v2/projects/:id
      - name: currency
        in: query
        description: Filter invoices by currency code
        schema:
          type: string
          example: USD
      - name: view
        in: query
        description: Filter invoices by view type
        schema:
          $ref: '#/components/schemas/InvoiceView'
      - name: updated_since
        in: query
        description: Show invoices updated since this date (YYYY-MM-DD)
        schema:
          type: string
          example: 2018-01-01
      - name: sort
        in: query
        description: Sort invoices by specified field
        schema:
          type: string
          enum:
          - updated_at
          - created_at
          example: updated_at
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
        default:
          $ref: '#/components/responses/ErrorResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
    post:
      tags:
      - Invoices
      summary: Create Invoice
      description: Create Invoice
      operationId: createInvoice
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                invoice:
                  $ref: '#/components/schemas/InvoiceCreatePayload'
            examples:
              Create Invoice:
                value:
                  invoice:
                    always_show_bic_and_iban: false
                    contact: https://api.freeagent.com/v2/contacts/:id
                    currency: GBP
                    dated_on: 2019-08-18
                    due_on: 2019-09-18
                    omit_header: false
                    payment_terms_in_days: 30
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
        default:
          $ref: '#/components/responses/ErrorResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
  /v2/invoices/{id}:
    get:
      tags:
      - Invoices
      summary: Show Invoice
      description: Show Invoice
      operationId: showInvoice
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
        default:
          $ref: '#/components/responses/ErrorResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
    put:
      tags:
      - Invoices
      summary: Update Invoice
      description: Update Invoice
      operationId: updateInvoice
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                invoice:
                  $ref: '#/components/schemas/InvoiceUpdatePayload'
            examples:
              Update Invoice:
                value:
                  invoice:
                    notes: An example of some additional text.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
        default:
          $ref: '#/components/responses/ErrorResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
    delete:
      tags:
      - Invoices
      summary: Delete Invoice
      description: Delete Invoice
      operationId: deleteInvoice
      responses:
        '200':
          description: Success
        '409':
          $ref: '#/components/responses/EmptyResponse'
        default:
          $ref: '#/components/responses/ErrorResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: string
        example: ''
  /v2/invoices/timeline:
    get:
      tags:
      - Invoices
      summary: Get invoice timeline
      description: Get invoice timeline
      operationId: getInvoiceTimeline
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
        default:
          $ref: '#/components/responses/ErrorResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
  /v2/invoices/{id}/pdf:
    get:
      tags:
      - Invoices
      summary: Show Invoice as PDF
      description: Show Invoice as PDF
      operationId: showInvoiceAsPdf
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
        default:
          $ref: '#/components/responses/ErrorResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: string
        example: ''
  /v2/invoices/{id}/send_email:
    post:
      tags:
      - Invoices
      summary: Send Invoice Email
      description: Send Invoice Email
      operationId: sendInvoiceEmail
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                invoice:
                  type: object
                  properties:
                    email:
                      $ref: '#/components/schemas/EmailPayload'
            examples:
              Send Invoice Email:
                value:
                  invoice:
                    email:
                      body: Bison bison bison bison bison Bison bison
                      from: Our Company <us@company.com>
                      subject: Testing
                      to: Test Contact <test_contact@example.com>
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
        default:
          $ref: '#/components/responses/ErrorResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: string
        example: ''
  /v2/invoice_items:
    post:
      tags:
      - Invoices
      summary: Create Invoice Item
      description: Create Invoice Item
      operationId: createInvoiceItem
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                invoice:
                  type: string
                  example: https://api.freeagent.com/v2/invoices/1
                invoice_item:
                  $ref: '#/components/schemas/InvoiceItemPayload'
            examples:
              Create Invoice Item:
                value:
                  invoice: https://api.freeagent.com/v2/invoices/1
                  invoice_item:
                    description: Fishing trip
                    item_type: Hours
                    price: 35
                    quantity: 6
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
        default:
          $ref: '#/components/responses/ErrorResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
  /v2/invoice_items/{id}:
    put:
      tags:
      - Invoices
      summary: Update Invoice Item
      description: Update Invoice Item
      operationId: updateInvoiceItem
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                invoice_item:
                  $ref: '#/components/schemas/InvoiceItemPayload'
            examples:
              Update Invoice Item:
                value:
                  invoice_item:
                    quantity: 3
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: string
        example: ''
  /v2/recurring_invoices:
    get:
      tags:
      - Recurring Invoices
      summary: List all recurring invoices
      description: List all recurring invoices
      operationId: listAllRecurringInvoices
      parameters:
      - name: view
        in: query
        description: Filter recurring invoices by view type
        schema:
          type: string
          enum:
          - draft
          - active
          - inactive
          example: draft
      - name: contact
        in: query
        description: Filter by contact URL
        schema:
          type: string
          example: https://api.freeagent.com/v2/contacts/:id
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
  /v2/recurring_invoices/{id}:
    get:
      tags:
      - Recurring Invoices
      summary: Show Recurring Invoice
      description: Show Recurring Invoice
      operationId: showRecurringInvoice
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: string
        example: ''
components:
  schemas:
    InvoiceView:
      type: string
      enum:
      - all
      - recent_open_or_overdue
      - open
      - overdue
      - open_or_overdue
      - draft
      - scheduled_to_email
      - thank_you_emails
      - reminder_emails
      - last_N_months
      example: all
    ExpensePayload:
      type: object
      properties:
        category:
          type: string
          example: https://api.freeagent.com/v2/categories/285
        created_at:
          type: string
          example: 2011-08-24 08:10:40+00:00
        currency:
          type: string
          example: USD
        dated_on:
          type: string
          example: 2011-08-24
        description:
          type: string
          example: Some description
        gross_value:
          type: string
          example: '-12.0'
        manual_sales_tax_amount:
          type: string
          example: '0.12'
        sales_tax_rate:
          type: string
          example: '20.0'
        updated_at:
          type: string
          example: 2011-08-24 08:10:40+00:00
        user:
          type: string
          example: https://api.freeagent.com/v2/users/1
    AttachmentPayload:
      type: object
      properties:
        data:
          type: string
          description: Binary data of the file encoded as base64
          example: iVBORw0KGgo...
        file_name:
          type: string
          example: receipt.pdf
        content_type:
          type: string
          enum:
          - image/png
          - image/x-png
          - image/jpeg
          - image/jpg
          - image/gif
          - application/x-pdf
          example: application/x-pdf
        description:
          type: string
          example: Invoice receipt
    InvoiceItemPayload:
      type: object
      properties:
        description:
          type: string
          example: Fishing trip
        item_type:
          type: string
          enum:
          - Hours
          - Days
          - Weeks
          - Months
          - Years
          - Products
          - Services
          - Training
          - Expenses
          - Comment
          - Bills
          - Discount
          - Credit
          - VAT
          - Stock
          example: Hours
        price:
          type: number
          example: 35
        quantity:
          type: number
          example: 6
    Errors:
      type: object
      additionalProperties: true
    BankTransactionExplanationCreatePayload:
      type: object
      properties:
        attachment:
          $ref: '#/components/schemas/AttachmentPayload'
        bank_account:
          type: string
          example: https://api.freeagent.com/v2/bank_accounts/1
        bank_transaction:
          type: string
          example: https://api.freeagent.com/v2/bank_transactions/8
        category:
          type: string
          example: https://api.freeagent.com/v2/categories/285
        dated_on:
          type: string
          example: 2010-05-01
        description:
          type: string
          example: harness end-to-end e-business
        gross_value:
          type: string
          example: '-730.0'
        paid_bill:
          type: string
          example: https://api.freeagent.com/v2/bills/123
        paid_invoice:
          type: string
          example: https://api.freeagent.com/v2/invoices/123
        paid_user:
          type: string
          example: https://api.freeagent.com/v2/users/1
        project:
          type: string
          example: https://api.freeagent.com/v2/projects/1
        rebill_factor:
          type: string
          example: '0.25'
        rebill_type:
          type: string
          example: markup
    BankTransactionExplanationUpdatePayload:
      type: object
      properties:
        attachment:
          $ref: '#/components/schemas/AttachmentPayload'
        category:
          type: string
          example: https://api.freeagent.com/v2/categories/285
        description:
          type: string
          example: Updated description
        gross_value:
          type: string
          example: '-730.0'
        paid_bill:
          type: string
          example: https://api.freeagent.com/v2/bills/123
        paid_user:
          type: string
          example: https://api.freeagent.com/v2/users/1
    BillCreatePayload:
      type: object
      properties:
        contact:
          type: string
          example: https://api.freeagent.com/v2/contacts/1
        reference:
          type: string
          example: REF100
        dated_on:
          type: string
          example: 2020-09-14
        due_on:
          type: string
          example: 2020-10-14
        comments:
          type: string
          example: Vehicle purchase
        ec_status:
          type: string
          example: UK
        attachment:
          $ref: '#/components/schemas/AttachmentPayload'
        bill_items:
          type: array
          items:
            $ref: '#/components/schemas/BillItemPayload'
    BillItemPayload:
      type: object
      properties:
        category:
          type: string
          example: https://api.freeagent.com/v2/categories/285
        description:
          type: string
          example: Item description
        total_value:
          type: string
          example: '300.0'
        sales_tax_rate:
          type: string
          example: '20.0'
    ContactCreatePayload:
      type: object
      properties:
        email:
          type: string
          example: fred@testingtonandsons.example.com
        first_name:
          type: string
          example: Frederick
        last_name:
          type: string
          example: Testington
        organisation_name:
          type: string
          example: Testington & Sons Ltd
    InvoiceCreatePayload:
      type: object
      properties:
        always_show_bic_and_iban:
          type: boolean
          example: false
        contact:
          type: string
          example: https://api.freeagent.com/v2/contacts/:id
        currency:
          type: string
          example: GBP
        dated_on:
          type: string
          example: 2019-08-18
        due_on:
          type: string
          example: 2019-09-18
        omit_header:
          type: boolean
          example: false
        payment_terms_in_days:
          type: number
          example: 30
    InvoiceUpdatePayload:
      type: object
      properties:
        notes:
          type: string
          example: An example of some additional text.
    EmailPayload:
      type: object
      properties:
        body:
          type: string
          example: Bison bison bison bison bison Bison bison
        from:
          type: string
          example: Our Company <us@company.com>
        subject:
          type: string
          example: Testing
        to:
          type: string
          example: Test Contact <test_contact@example.com>
  responses:
    EmptyResponse:
      description: Error response
    ErrorResponse:
      description: Error response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
    UnauthorizedResponse:
      description: Unauthorized - Authentication required or invalid credentials
  securitySchemes:
    oauth2:
      type: oauth2
      flows: {}
security:
- oauth2: []
tags:
- name: Bank Accounts
- name: Bank Transaction Explanations
- name: Bank Transactions
- name: Bills
- name: Categories
- name: Company
- name: Contacts
- name: Expenses
- name: Invoices
- name: Invoice Transitions
- name: Recurring Invoices
